# Generated by Django 4.1.1 on 2022-10-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_alter_owner_options_alter_owner_contact_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="contact_name",
            field=models.CharField(default=1, max_length=200, verbose_name="ФИО"),
            preserve_default=False,
        ),
    ]
