# Generated by Django 4.1.1 on 2022-11-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0005_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="date_now",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата создания"),
        ),
    ]
