# Generated by Django 4.1.1 on 2022-11-04 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0007_alter_feedback_date_now"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="date_now",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Дата создания"
            ),
        ),
    ]
