# Generated by Django 4.1.1 on 2022-11-04 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0008_alter_feedback_date_now"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="date_now",
            new_name="date_create",
        ),
    ]
